import Testing
import Foundation
import CoreGraphics
import ImageIO
@testable import LightboxCore

/// The same 32-bit LCG used to generate the golden vector from photolib:
/// s = (s * 1664525 + 1013904223) mod 2^32, sample = s >> 24.
private func lcgGrid(seed: UInt32) -> [UInt8] {
    var s = seed
    return (0..<1024).map { _ in
        s = s &* 1_664_525 &+ 1_013_904_223
        return UInt8(truncatingIfNeeded: s >> 24)
    }
}

private func rampGrid() -> [UInt8] {
    (0..<1024).map { (i: Int) -> UInt8 in
        let x = i % 32
        let y = i / 32
        return UInt8((x * 7 + y * 13) % 256)
    }
}

private let sipsAvailable = FileManager.default.isExecutableFile(atPath: "/usr/bin/sips")

/// A `struct` suite so swift-testing builds a fresh instance per test and
/// releases it afterwards: teardown of `tree` is then the framework's
/// contract rather than an ARC ordering inferred from where it was last used.
struct PerceptualHashTests {
    let tree: TempTree

    init() throws {
        tree = try TempTree()
    }

    @Test func matchesPhotolibGoldenVectors() throws {
        // Generated by photolib's lib/phash.js. If these change, the two tools no
        // longer agree and every cached hash in either is invalidated.
        #expect(try PerceptualHash(gray: lcgGrid(seed: 12345)).hex == "9f32a3b705ae1b18")
        #expect(try PerceptualHash(gray: rampGrid()).hex == "1b6b0a6ed5c45ab4")
    }

    @Test func theLCGGridMatchesTheGeneratorUsedForTheGoldenVector() {
        #expect(Array(lcgGrid(seed: 12345).prefix(8)) == [5, 4, 139, 162, 232, 28, 126, 140])
    }

    @Test func aFlatGridHashesToZero() throws {
        // Degenerate but correct: every retained coefficient is zero, so none
        // exceeds the median. Documented so a future reader does not "fix" it.
        #expect(try PerceptualHash(gray: [UInt8](repeating: 128, count: 1024)).hex
                == "0000000000000000")
    }

    @Test func identifierAndGridSizeAreLockedToPhotolib() {
        #expect(PerceptualHash.identifier == "phash-dct-64-nodc")
        #expect(PerceptualHash.gridSize == 32)
    }

    @Test func rejectsAGridOfTheWrongSize() {
        for grid in [[UInt8](repeating: 0, count: 100), []] {
            let error = #expect(throws: HashError.self) { try PerceptualHash(gray: grid) }
            guard case .malformed = error else {
                Issue.record("expected .malformed for \(grid.count) samples, got \(String(describing: error))")
                return
            }
        }
    }

    @Test func hexRoundTripsAndDistanceIsSymmetric() throws {
        let a = try PerceptualHash(gray: lcgGrid(seed: 12345))
        let b = try PerceptualHash(hex: a.hex)
        #expect(a == b)
        #expect(a.distance(to: b) == 0)

        let c = try PerceptualHash(gray: rampGrid())
        #expect(a.distance(to: c) == c.distance(to: a))
        #expect(a.distance(to: c) == 28)      // measured against photolib
    }

    @Test func rejectsMalformedHex() {
        for text in ["nothex", "abc", "0123456789abcdef00"] {
            let error = #expect(throws: HashError.self) { try PerceptualHash(hex: text) }
            guard case .malformed = error else {
                Issue.record("expected .malformed for \(text), got \(String(describing: error))")
                return
            }
        }
    }

    @Test func rendererProducesAGridOfExactlyTheRightSize() throws {
        let url = try Fixtures.writeImage(to: tree.root.appendingPathComponent("a.jpg"),
                                          width: 400, height: 130)
        let gray = try GrayscaleRenderer().gray32(from: url)
        #expect(gray.count == 1024)
    }

    @Test func rendererIsDeterministicForTheSameFile() throws {
        let url = try Fixtures.writeImage(to: tree.root.appendingPathComponent("a.jpg"))
        #expect(try GrayscaleRenderer().gray32(from: url) == GrayscaleRenderer().gray32(from: url))
    }

    @Test func rendererThrowsForANonImage() throws {
        let url = tree.root.appendingPathComponent("junk.jpg")
        try Data("not an image".utf8).write(to: url)
        #expect(throws: MetadataError.notAnImage) { try GrayscaleRenderer().gray32(from: url) }
    }

    @Test func differentImagesProduceDistantHashes() throws {
        let a = try Fixtures.writeImage(to: tree.root.appendingPathComponent("a.jpg"), seed: 0)
        let b = try Fixtures.writeImage(to: tree.root.appendingPathComponent("b.jpg"), seed: 128)
        let ha = try PerceptualHash(gray: GrayscaleRenderer().gray32(from: a))
        let hb = try PerceptualHash(gray: GrayscaleRenderer().gray32(from: b))
        #expect(ha.distance(to: hb) > 8)
    }

    @Test(.enabled(if: sipsAvailable, "sips not available"))
    func aRecompressedCopyStaysClose() throws {
        let original = try Fixtures.writeImage(to: tree.root.appendingPathComponent("a.png"),
                                               format: .png, width: 320, height: 240)
        // Re-encode as a low-quality JPEG.
        let recompressed = tree.root.appendingPathComponent("a-lowq.jpg")
        let sips = Process()
        sips.executableURL = URL(fileURLWithPath: "/usr/bin/sips")
        sips.arguments = ["-s", "format", "jpeg", "-s", "formatOptions", "30",
                          original.path, "--out", recompressed.path]
        sips.standardOutput = FileHandle.nullDevice
        sips.standardError = FileHandle.nullDevice
        try sips.run(); sips.waitUntilExit()
        try #require(sips.terminationStatus == 0)

        let a = try PerceptualHash(gray: GrayscaleRenderer().gray32(from: original))
        let b = try PerceptualHash(gray: GrayscaleRenderer().gray32(from: recompressed))
        // The whole point of a perceptual hash: quality loss must not move it far.
        #expect(a.distance(to: b) <= 8)
    }
}
